### ISSUE TITLE
E

### ISSUE THREAD

**Issue by eruci** [EOS-Nation/Members#11]
## Joining EOS Nation

Provide the following information to submit your candidacy to become a member of EOS Nation.
Applicants will have to forgo a public review process by the EOS Nation community and once a consensus has been reached the member will be brought on board the EOS Nation community.

- [x] Ervin Ruci
- [x] Ottawa, ON Canada
- [ ] ![Avatar](https://avatars3.githubusercontent.com/u/601910?s=88&v=4)
- [ ] I'm Ervin Ruci, an  [45.31613,-75.60717](https://geocode.xyz/45.31613,-75.60717)  based developer and "entrepreneur" (since 2005 - the year I quit my last day job and completed my MSC in Computational Geometry.) 
- [ ] Technology
- [ ] Social Media Accounts (Optional)
  - [ ] Twitter: @geolytica

**Comment by DenisCarriere** [comment]
👋 Hey @eruci ! Glad you're able to submit your name to our EOS Nation group.

@EOS-Nation/community I'm recommending @eruci to be on board to help out on the Technology/Blockchain Protocols, I've got a few ideas on how to incorporate OpenStreetMap on the Blockchain, however I won't be able to tackle this myself (maybe @JC0112 will also have some ideas).

I know you're no a "bio" type of person, but gathered up a small bio for you:

## Bio

Founder of Geocode.xyz (Geoparse & Geocode platform) Currently working on extracting geolocations from books & articles using Machine Learning.

**Comment by DenisCarriere** [comment]
Welcome 👋 @eruci I've added you to our Ambassador list with a role of `GIS Blockchain Protocol`, hopefully in the coming weeks we can define a bit more how we would be able to implement an OSM like database onto the Blockchain.

https://github.com/EOS-Nation/Ambassadors/blob/master/README.md#current-ambassador-team
