### ISSUE TITLE
EOS Nation Ambassador + anything related to finance and strategy

### ISSUE THREAD

**Issue by lapapanite** [EOS-Nation/Members#12]
- [Papy Bakayoko ] Full Name
- [ Montreal Canada] Geographical Location
- [<script src="https://gist.github.com/lapapanite/746a9cd0bf8b40ac7f14bbe5396145f9.js"></script> ] Headshot image
- [Curious mind evolving in the finance industry as portfolio manager in an asset management firm. I Like to ski, get some shot at the basket or read during my spare time.  I had my aha moment the first time I read about the concept of smart contract, totally impressed by the level of disruption the blockchain technology could bring to the finance industry and to the overall organization of our society. 
If I was able to envision the disruptive potential of the technology, scalability and governance issues made me feel doubtful about the viability of the DLT until i came across the EOS white paper. Then all the pieces of the puzzle came together,  EOS is being built by an experienced team with a clear vision, solving the scalability and governance issues to harness the benefits of decentralization to secure the values that are dear to us liberty and property right.  
I'm here too give my contribution to this endeavor, increase the awareness about the blockchain, share the knowledge and help grow the community of developers on the platform] Bio (Description of yourself)

- [ Meetup organizer: I've read a lot about different blockchain protocols and grasped a good knowledge base to put forward the strong points of EOS relative to other blockchains  protocols and defend the vision chosen by EOS.
  Venture Cap:  Strong background in finance CFA charter holder, good experience and network we could leverage. I have been involved with different types of companies in various industries for instance the Star group at various level from first warrant financing as AMAYA gaming till LBO purchase of Pokerstar. good network within the financial industry in Montreal and Toronto] Proposed Role and why should we choose you?
- [ ] Social Media Accounts (Optional)
  - [ Layimoussa-moini Lapapanite] Facebook
  - [ lapapanite] Steemit
  - [Papa Mamadou Bakayoko ] LinkedIn
  - [ ] Twitter
  - [ ] GitHub
  - [LMMLPP ] Telegram

**Comment by DenisCarriere** [comment]
EOS Nation `members.md` has been changed to Ambassadors (transferred on behalf of @lapapanite)

Request has been transferred to => https://github.com/EOS-Nation/Ambassadors/issues/2
