### ISSUE TITLE
Jan Langheimer - new member application

### ISSUE THREAD

**Issue by pingustar** [EOS-Nation/members#4]
# Jan Langheimer

## Bio
Born and raised in Germany. In Toronto since 2016. Web Developer. Ethereum Miner. DevOps. EOS Fanboy.

## Role
+  ⭐️ EOS Toronto Meetup Co-Host 
+  ⭐️ [EOSindex.io](https://eosindex.io) Founder

## SocialMedia
+  [Twitter](https://twitter.com/JanLghr)
+  [Telegram](https://t.me/pinguSTAR)

**Comment by DenisCarriere** [comment]
Thank you @pingustar for applying to EOS Nation.

Looking forward to grow the EOS Toronto community.

**Comment by DenisCarriere** [comment]
@pingustar Welcome on board the EOS Nation core members! 🚀

A PR will follow shortly and you will be added to the `members.md` list.
