### ISSUE TITLE
David Requenez

### ISSUE THREAD

**Issue by DAVEREX86** [EOS-Nation/members#8]
## Joining EOS Nation

Provide the following information to submit your candidacy to become a member of EOS Nation.
Applicants will have to forgo a public review process by the EOS Nation community and once a consensus has been reached the member will be brought on board the EOS Nation community.

- [ ] David Requenez
- [ ] Texas, USA
- [ ] Headshot image
![1](https://user-images.githubusercontent.com/32780484/36948698-5dcc4510-1fa4-11e8-8689-f3a756862c06.png)

- [ ] I’ve lived in Texas all my life and am of Hispanic heritage, a 3rd generation college graduate and earned an MBA in 2011, acquired experience in education/education administration and worked business startups in education and design.  I’ve had an eye in the blockchain space for a while, the first opportunity I missed was not buying Bitcoin when I saw it at $2, I started getting interested in it again when it dropped below $500 and have been investing in the space ever since.   I followed big names in the industry (Andreas Antonopoulos) and was a bitcoin maximalist for a long time, then I realized Bitcoin was no longer making sense as a P2P money or scaling solution due to miner control and fees.  I came across EOS just for the mere fact that It was relatively cheap, just dropping from just above $5.  I jumped in at about $1.75 and double down every time it dropped (closely following the project)… so yea 100% of my cryptfolio is EOS.  I’ve always been a saver and investor but never really made money until the cryptoworld came around… I was and still am convinced that markets are manipulated.  I Iived through the Internet boom, housing bust, and Financial Crisis, am an original RON PAUL 2008 supporter and am driven to study free market economics, a big fan of Peter Schiff, Marc Faber & Milton Friedman.  I also enjoy and try to stay on the forefront of technology (some experience in web design & coding), so when I saw the man Dan Larimer come about (boom) All in (free market solutions).  I see Dan Larimer as the Steve Jobs of Crypto.  Other than this, I’m a pretty basic guy with a passion for business development and community growth and engagement.  Behind every great project is are great people and a community to support them.
- [ ] Role
Facebook EOS Nation (Admin)
Community Engagement
Design
- [ ] Social Media Accounts
  - [ ] Steemit https://steemit.com/@daverex
  - [ ] LinkedIn   https://www.linkedin.com/in/david-requenez-mba-7697a644/
  - [ ] Twitter     https://twitter.com/DaveRex
  - [ ] GitHub   https://github.com/DAVEREX86
  - [ ] Telegram   DAVE REX

**Comment by DenisCarriere** [comment]
Thanks @DAVEREX86 for providing all the required contact information.

You've been added to the `members.md` list 👍 🚀

**Comment by DenisCarriere** [comment]
Feel free to update your profile bio as required:

https://github.com/EOS-Nation/members/blob/master/members.md#david-requenez
